src/views/blue_user.py
# -*- coding: UTF-8 -*-
#FLASK
from flask import Flask, render_template, url_for, jsonify, \
redirect, request, make_response, Blueprint, current_app
#Usuarios en Bases de Datos
from mongo_user import UserManager
from mongo_oauth import OAuthUserManager
#importo en no_cookie_check
#necesario para evitar que me rediriga
#a la pantalla de login si no he iniciado
#sesion
from blue_cookie import no_cookie_check
#credenciales oauth (clientid)
from blue_oauth import getClientId
#Log
import logging
from log_handler import setup_log, setStreamMode

blueUser = Blueprint('blueUser', __name__)

"""
  ____            _     _             
 |  _ \ ___  __ _(_)___| |_ _ __ ___  
 | |_) / _ \/ _` | / __| __| '__/ _ \ 
 |  _ <  __/ (_| | \__ \ |_| | | (_) |
 |_| \_\___|\__, |_|___/\__|_|  \___/ 
            |___/                     
"""
#Registro.
#Registro de usuarios de forma local. Los usuarios OAuth se
#registran el a ruta /jsoauthdata accesible desde 
#/jsoauthlogin.
#Obtenemos datos del cliente y creamos cuenta a partir
#de los mismos.
@blueUser.route("/register", methods=['GET','POST'])
@no_cookie_check
def webRegister():
    logging.debug("/register - METODO: " + str(request.method))

    #GET
    if request.method=='GET':
        return render_template("register.html")

    #POST
    if request.method=='POST':
        logging.debug("/register - Estoy en POST")
        username=str(request.form['username'])
        password=str(request.form['password'])
        umbral=float(request.form['umbral'])

        #Creo instancia del manejador de usuarios local
        UserHandler = UserManager()
        #Creacion usuario. Obtengo codigo indicando el resultado en 'exito'.
        exito=UserHandler.createUser(username,password,umbral)
        #url a la que redirigir al cliente si se registra al 
        #usuario correctamente.
        url = url_for('blueUser.webLogin')
        #Datos a enviar al cliente en forma de JSON.
        #Deben tener el formato:
        #{"url" : url_a_redireccionar, 
        #"code": codigo del resultado de la operacion}
        datos={'url': url, 'code': exito}
        logging.debug("RESPUESTA SERV: " + str(datos))
        #Creo la respuesta para el cliente.
        #Contendrá los datos en forma JSON
        response=make_response(jsonify(datos))

        #Le envio info sobre el resultado de la operacion y
        #la pagina web a donde hay que redirigir en caso de
        #craecion satisfactoria.
        #Este mensaje es interpretado por el cliente mediante javascript,
        #de forma que si exito==0 redirige a url_for('webLogin')
        return response

"""
  _                _       
 | |    ___   __ _(_)_ __  
 | |   / _ \ / _` | | '_ \ 
 | |__| (_) | (_| | | | | |
 |_____\___/ \__, |_|_| |_|
             |___/         
"""
#Login
@blueUser.route("/login", methods=['GET','POST'])
@no_cookie_check
def webLogin():
    if request.method == 'GET':
        #CLIENT_ID="324401899197-2cag1rbuoium6s2q96m1i0hm3fjium4g.apps.googleusercontent.com"
        CLIENT_ID=getClientId()
        return render_template("login.html",id_api=CLIENT_ID)

    elif request.method == 'POST':
        #Los convierto a string pues estrán en tipo 'unicode'
        user=str(request.form['user'])
        #user=request.args.get('user','default',type=str)
        passw=str(request.form['pass'])
        #passw=request.args.get('pass','default',type=str)
        
        #DEBUG
        logging.debug("DEBUG - /login")
        logging.debug("user - type: " + str(type(user)))
        logging.info("user: " + str(user))
        logging.debug("pass - type: " + str(type(passw)))
        logging.info("pass: " + str(passw))

        #Creo la respuesta que devolveré al cliente.
        #Esta respuesta estrá compuesta por el resultado
        #devuelto por la función render_template().
        #A esta respuesta le añadiré la cookie generada como resultado del 
        #inicio de sesión, si este es satisfactorio.
        #resp = make_response(redirect(url_for('blueApp.webMain')))

        #Creo instancia del manejador de usuarios local
        UserHandler = UserManager()
        #Obtengo cookie resultado de log in
        cookieVal=UserHandler.login(user,passw)
        #Si se ha iniciado sesion, el valor de 
        #cookieVal será != -1
        #---JSON
        #url a,la que redireccionar
        url = url_for('blueApp.webMain')
        if cookieVal >=0:
            exito = 1
        else:
            exito = 0
        #Datos a enviar al cliente en forma de JSON.
        #Deben tener el formato:
        #{"url" : url_a_redireccionar, 
        #"code": codigo del resultado de la operacion}
        datos={'url': url, 'code': exito}
        logging.debug("RESPUESTA SERV: " + str(datos))
        resp = make_response(jsonify(datos))
        #---
        #Añado cookies a la respuesta
        resp = setLoginCookies(resp, cookieVal)
        #return redirect(url_for('blueApp.webMain'))
        return resp

#Añado credenciales a la respuesta
#solo si se ha iniciado sesion 
#correctamente (cookieVal >=0).
def setLoginCookies(resp, cookieVal):
    if cookieVal >= 0:
        #Creo instancia del manejador de usuarios local
        UserHandler = UserManager()
        #Asigno cookies
        resp.set_cookie('SessionId', cookieVal)
        resp.set_cookie('tipoLogin', 'local')
        #también pongo umbral en la cookie, para notificaciones
        nombreUsuario = UserHandler.getCookieUserName(cookieVal)
        umbralUsuario = UserHandler.getUmbral(nombreUsuario)
        resp.set_cookie('umbral', str(umbralUsuario))
    return resp

"""
  _                            _   
 | |    ___   __ _  ___  _   _| |_ 
 | |   / _ \ / _` |/ _ \| | | | __|
 | |__| (_) | (_| | (_) | |_| | |_ 
 |_____\___/ \__, |\___/ \__,_|\__|
             |___/                 
"""

#Logout
@blueUser.route("/logout")
def webLogout():
    #Obtengo info de las cookies
    idSesion=request.cookies.get('SessionId')
    #tipo de login
    idTipo=request.cookies.get('tipoLogin')
    #OAUTH
    if idTipo=="oauth":
        #Creo instancia del manejador de usuarios OAuth
        OAuthHandler = OAuthUserManager()
        #Logout al usuario
        logging.info("(OAuth)logging out user: " + idSesion)
        OAuthHandler.logout(idSesion)
    #LOCAL
    elif idTipo=="local":
        logging.info("(Local)logging out user: " + idSesion)
        #Creo instancia del manejador de usuarios local
        UserHandler = UserManager()
        #Logout al usuario
        UserHandler.logout(idSesion)

    #Retornamos a la pag de login
    response=make_response(redirect(url_for('blueUser.webLogin')))
    #Borramos datos cookies
    response.set_cookie('umbral', '', expires=0)
    return response
    

"""
  _   _           _               _ 
 | | | |_ __ ___ | |__  _ __ __ _| |
 | | | | '_ ` _ \| '_ \| '__/ _` | |
 | |_| | | | | | | |_) | | | (_| | |
  \___/|_| |_| |_|_.__/|_|  \__,_|_|
                                    
"""
#CAMBIAR umbral del usuario
@blueUser.route('/cambiarUmbral', methods=['GET','POST'])
def cambiarUmbral():
    logging.debug("/cambiarUmbral - METODO: " + str(request.method))
    response = make_response("cambiarUmbral_placeholder")
    #Obtengo info de las cookies
    idSesion=request.cookies.get('SessionId')
    #tipo de login
    idTipo=request.cookies.get('tipoLogin')
    #inicio variables en caso de que no haya cookies en el cliente
    nombreUser=None
    nombreAMostrar=None
    #Creo instancia del manejador de usuarios local
    UserHandler = UserManager()
    #Creo instancia del manejador de usuarios OAuth
    OAuthHandler = OAuthUserManager()
    #OAUTH
    if idTipo=="oauth":
        nombreUser=OAuthHandler.getCookieUserName(idSesion)
        nombreAMostrar=OAuthHandler.getUserName(nombreUser)
    #LOCAL
    elif idTipo=="local":
        nombreUser=UserHandler.getCookieUserName(idSesion)
        nombreAMostrar=nombreUser
    #-------
    #GET
    if request.method == 'GET':
        response = render_template('changeUserUmbral.html',
        username=nombreAMostrar)

    #POST
    elif request.method == 'POST':
    #else:
        logging.debug("Estoy en POST")
        
        #umbral=request.form['umbral']
        umbral=request.form.get('umbral',101)
        #umbral = request.args.get('umbral', 101, type=float)
        #
        #resquest.args.get es mucho mejor, si no encuentra el argumento
        #'umbral' en vez de lanzar una excepcion da un valor por defecto,
        #el cual podemos especificar, asi como su tipo.
        #
        #INCORRECTO. request.args.get se emplea cuando se envian
        #parametros mediante GET (los cuales estarán incluidos en la
        #url).
        #Lo que es mejor que request.form[<nombreParam>] es 
        #request.form.get(<nombreParam>, defaultValue), ya que de 
        #esta forma, si no estan los parametros que intentamos
        #obtener, la funcion nos devolverá el valor por defecto
        #especificado en vez de 'None'.
        logging.debug("UMBRAL RECIBIDO: " + str(umbral))
        logging.debug("tipo: " + str(type(umbral)))
        try:
            umbral=float(umbral)
        except ValueError:
            umbral=101
        #CAMBIO UMBRAL DEL USUARIO.
        if idTipo=="oauth":
            OAuthHandler.modUmbral(nombreUser, umbral)
            #response=make_response("UMB:"+str(OAuthHandler.getUmbral(nombreUser)))
            umbralDef = OAuthHandler.getUmbral(nombreUser)
            #response=make_response("UMB:"+str(umbralDef))
        elif idTipo=="local":
            UserHandler.modUmbral(nombreUser, umbral)
            #response=make_response("UMB:"+str(UserHandler.getUmbral(nombreUser)))
            umbralDef = UserHandler.getUmbral(nombreUser)
            #response=make_response("UMB:"+str(umbralDef))
        else:
            #EL usuario no ha hecho login.
            #
            #Los codigos de error de getUmbral() son:
            #-> 102: El usuario es 'None'. Es el valor que se obtiene cuando no se ha

src/templates/DBselect.html
{# DBselect.html #}
{% extends "topbar_base.html" %}
{% block cabeza %}
	{# Importo script para hacer post
    de la opcion elegida del menú principal
    y para redireccionar a la url recibida
    del servidor como respuesta.#}
    <script 
    src= "{{ url_for('static',filename='js/enviarOpcionMenu.js') }}">
    </script>
    {# Necesitada por enviarOpcionMenu.js. Se emplea para evaluar las respuestas
    recibidas del servidor.#}
    <script 
    src= "{{ url_for('static',filename='js/respuestasServidor.js') }}">
    </script>
{% endblock %}

{% block cuerpo %}
<title>Selección DB</title>
<div><p>Selecciona base de datos:</p></div>
<br>
<br>
    {#
    <button 
        type = "button"
        class="botonMenu" 
        opcion="MySQL"
        >MySQL</button>
    <br>
    #}
    <button 
        type = "button"
        class="botonMenu" 
        opcion="MongoDB"
        >Local (MongoDB)</button>
    <br>
    <button 
        type = "button"
        class="botonMenu" 
        opcion="Beebotte"
        >Remota (Beebotte)</button>

<script>
    //enviarOpcionBotones();
    var listaBotones = $(".botonMenu");
    var atrib = "opcion"
    enviarOpcionMenu(listaBotones, atrib);
</script>
{% endblock %}

src/templates/about.html
{# accountInfo.html #}
{% extends "topbar_base.html" %}
{% block cuerpo %}
    <title>Acerda de Random-Lender</title>
    <div id="divAbout">
    <h1>Random-Lender</h1>
    <p>
    <span>Random_Lender es una aplicación web que obtiene números aleatorios de
    la web </span><a
    href="http://www.numeroalazar.com.ar/">numeroalazar.com.ar</a>
    <span> y los almacena en diferentes bases de datos:</span>
    </p>
    <ul>
        <li><p>MongoDB (local)</p></li>
        <li><p>Beebotte (online)</p></li>
        <li><p><span>MySQL </span><del>(local)</del>
        <span>(obsoleto)</span></p></li>
    </ul>
    <p>Random_lender nos permite realizar ciertas operaciones con los números
    almacenados:</p>
    <ul>
        <li><p><b>Obtener número aleatorio</b></p><p>Se nos muestra un numero
        aleatorio alamcenado en la base de datos.</p></li>
        <li><p><b>Mostrar tabla</b></p><p>Nos muestra una tabla con todos los números en la
        base de datos y sus respectivas fechas de obtención.</p></li>
        <li><p><b>Umbral</b></p><p>Indicado un número como umbral, se nos indicará cuál
        es el último número alamacenado en las bases de datos que lohaya superado
        tanto por arriba como por abajo.</p></li>
        <li><p><b>Media</b></p><p>Muestra la media de los números almacenados en las bases
        de datos.</p></li>
        <li><p><b>Gráficas Remotas</b> (Beebotte):</p><p>Muestra gŕaficas de la web de Beebotte.</p></li>
        <li><p><b>Gráficas Locales</b> (Plotly):</p><p> Muestra gráfica de los números aleatorios registrados.
        También permite mostrar gráfico de barras con las frecuencias de los
        números por intervalos. Se emplea la librería de plotly para javascript.</p></li>
    </ul>
    
    <p>Random-Lender también nos avisará cuando se haya registrado un número que
    active el umbral del usuario, es decir, que sea mayor que el umbral del
    usuario (puede cambiarse en el apartado de cuenta, opción en la barra
    superior de la aplicación).</p>
    
    <h2>Umbrales de Usuario</h2>

    <p>Los umbrales funcionan de la siguiente manera:</p>
    <ul>
        <li><p>Un umbral debe estar comprendido entre 0 y 100
        para que sea válido.</p></li>
        <li>
            <p>La aplicación notificará al 
            usuario cuando se registre un número mayor que el umbral 
            que haya especificado.</p>
            <p>Ejemplo:
            <br>
            <span>Umbral Usuario: <b>50</b></span>
            <br>
            <span>Número registrado: 40 &#8594; 40 &lt; 50 &#8594; <b>No</b> avisa</span>
            <br>
            <span>Número registrado: 60 &#8594; 60 &gt; 50 &#8594; <b>Avisa</b></span>
            </p>
        </li>
    </ul>
    </div>
{% endblock %}

src/templates/accountInfo.html
{# accountInfo.html #}
{% extends "topbar_base.html" %}
{% block cabeza%}
{# IMPORTAR SCRIPT #}
    <script 
        src="{{ url_for('static', filename='js/adaptAccountPage.js') }}">
    </script>
{% endblock %}
{% block cuerpo %}
    <title>Información Cuenta</title>
    <div class="userInfoBlock">
        <h1>Informacion:</h1>
        <div class="userInfoDiv">
            <span>Nombre: </span> 
            <span class="userInfo">{{ nombrehtml }}</span>
        </div>
        <div class="userInfoDiv">
            <span>E-mail: </span> 
            <span class="userInfo">{{ emailhtml }}</span>
        </div>
        <div class="userInfoDiv">
            <span>Proveedor: </span> 
            <span class="userInfo">{{ proveedorhtml }}</span>
        </div>
        <div class="userInfoDiv">
            <span>Umbral: </span> 
            <span class="userInfo">{{ umbralhtml }}</span> 
            {#<button 
            onclick="window.location.href='/cambiarUmbral'">Cambiar Umbral
            </button>#}
            <a href='{{url_for("blueUser.cambiarUmbral")}}'>Cambiar Umbral</a>
        </div>
        <br>
        <div class="userInfoDiv">
            <span>Tipo registro: </span> 
            <span class="userInfo">{{ tipoRegistrohtml }}</span>
        </div>

    </div>
    
    <script>
        checkCamposVacios(document.getElementsByClassName('userInfoBlock')[0])
    </script>

{% endblock %}

src/templates/beebotte.html
{# media.html #}
{% extends "topbar_base.html" %}
{% block cabeza%}
	
  <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/jquery-ui.css') }}">
  <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/style.css') }}">

{# biblioteca Beebotte #}
<script src='{{ url_for('static', filename='js/bbt.js') }}'>
</script>
{# dependencia de la biblioteca Beebotte #}
<script src='{{ url_for('static', filename='js/socket.io.js') }}'>
</script>
{#DIALOGS#}
	<script src='{{ url_for('static', filename='js/jquery-ui.js') }}'></script>
  <script>
  $( function() {
    $( "#dialog" ).dialog({
      autoOpen: false,
      modal: true,
      buttons: {
        "dialogButton":{ 
            text: "Ok",
            id: "dialogOkBoton",
            click: function() {
              $( this ).dialog( "close" );
            }
        }
      },
      show: {
        effect: "blind",
        duration: 100
      },
      hide: {
        effect: "blind",
        duration: 100
      }
    });
 
    $( "#opener" ).on( "click", function() {
      $( "#dialog" ).dialog( "open" );
    });
  } );
  </script>
{% endblock %}
{% block cuerpo %}
<title>Gráficas Beebotte</title>
<div><h2>Gráficas Beebotte:</h2></div>
<div id="dialog" title="Basic dialog">
  <p>This is an animated dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
</div>
 
<button id="opener">Open Dialog</button>
<br>
<div id="graficaBee">
Hola buenas dias
</div>
<div>
    {% raw %}
    <span> This is the number: {{ NumberList.numero }} </span>
    {% endraw %}
</div>
<script>
    var canal = "NumberList"
    var res = "numero"
    {% raw %}
        //$("#graficaBee").html({{ canal.res }})
    {% endraw %}
    $("span#linkaux").click(function(){window.open("https://beebotte.com/dash/09db3e70-df3a-11e7-bfef-6f68fef5ca14");})

</script>

{% endblock %}

src/templates/changeUserUmbral.html
{# changeUserUmbral.html #}
{% extends "topbar_base.html" %}
{% block cabeza %}
    {# Cargo Script para la comprobación de datos#}
    <script 
    src="{{ url_for('static', filename='js/enviarUmbral.js') }}">
    </script>
    {# Script necesitado por enviarUmbral.js para interpretar
    respuestas del servidor#}
    <script 
    src="{{ url_for('static', filename='js/respuestasServidor.js') }}">
    </script>
{% endblock %}

{% block cuerpo %}
    <form 
    id="form_umbral" 
    action="{{url_for('blueUser.cambiarUmbral')}}" 
    method="POST">
        <p>Elige tu umbral: {{ username }}</p>
        <p>Debe ser un número comprendido entre 0 y 100.</p>
        <input type="text" id="umbral" name="umbral" required="true">
        <button type="submit" id="botonUmbral">Enviar</button>
    </form>
    <script>
        var selector = "#form_umbral";
        enviarUmbralForm(selector);
    </script>
{% endblock %}

src/templates/grafo.html
{# grafo.html #}
{% extends "topbar_base.html" %}
{% block cabeza %}

    <title>Grafo {{nombreDBSimple}}</title>
    <!--Necesario para que Flask lea adecuadamente la grafica generada-->
    <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js">
    </script>
    <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/pygal-tooltips.js">
    </script>
{% endblock %}

{% block cuerpo %}
    <div>Seleccione tipo de grafo: <div>
    <br>
<!--Formulario utlizado para seleccionar el tipo de grafo-->
    <form action="{{ url_for('createGraph_post') }}" method="POST">
        <select name="graphType">
            <option value="line">GrafoLineas</option>
            <option value="bar">GrafoBarras</option>
        <input type="submit" name="refrescar" value="Refrescar"><br>
    </form>

<br>
<!--Hay que poner el '| safe' detrás de la variable para que Flask la interprete como código HTML-->
{{ graph_data | safe }}
<br>
    <div>Base de datos empleada: {{DBName}}</div>
<br>
    <form action="{{ url_for('createGraph_post') }}" method="POST">
        <input type="submit" name="volver" value="Menú Principal"><br>
    </form>
{% endblock %}

src/templates/grafoBee.html
{# media.html #}
{% extends "topbar_base.html" %}
{% block cuerpo %}
<title>Gráficas Beebotte</title>
<h2>Gráficas Beebotte:</h2>
<br>
{#Se creará una tabla con el umbral en este elemento#}
<div id="result">
</div>
<span> Se te va a redirigir fuera de la web. Si quieres continuar </span>
<a
href="https://beebotte.com/dash/84a2bb80-df29-11e7-bfef-6f68fef5ca14">Haz
click aquí</a>
<span id="linkaux">o aquí.</span>
<br>

<iframe id="grafoBee" src="https://beebotte.com/embed/dash/84a2bb80-df29-11e7-bfef-6f68fef5ca14"></iframe>

<script>

$("span#linkaux").click(function(){window.open("https://beebotte.com/dash/84a2bb80-df29-11e7-bfef-6f68fef5ca14");})

</script>

{% endblock %}

src/templates/jsoauthlogin.html
{# jsoauthlogin.html #}
{% extends "topbar_empty_base.html" %}

{% block cabeza_base %}
    {#<meta name="google-signin-client_id"
    content="933060102795-0hf4m6v3cuq4ocvubaide7ouqui2l4lg.apps.googleusercontent.com">#}
    <meta name="google-signin-client_id" 
    content="{{id_api}}">
    {# Cargo Scripts Google Oauth2 para utilizar con los botones #}
    <script type=text/javascript src="{{ url_for('static', filename='js/oauth_functions.js') }}"></script>
{% endblock %}

{% block cuerpo_base %}
    <h1>Google OAuth2 Sign in</h1>
    
    {# Load the Google Platform Library #}
    {#<script src="https://apis.google.com/js/platform.js" async defer></script>#}
    {# Default Google Sign in Button #}
    {#
    <div class="g-signin2" data-onsuccess="onSignIn"
    onclick="validarSignIn()"></div>
    #}
    {# Custom Google Sign in Button #}
    <div id="my-signin2"
    onclick="validarSignIn()"></div>
    {# Load the Google Platform Library #}
    {#La function renderButton() está definida en pauth_functions.js. Sirve
    para darle estilo al botón.#}
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
    <br>
    <a href="{{url_for('blueUser.webLogin')}}">Atrás</a>

    {#-----------------------#}
    {# Boton Sign out #}
    {#
    <button type="button" onclick="signOut();">Sign Out</button>
    #}

{% endblock %}

src/templates/login.html
{# login.html #}
{% extends "topbar_empty_base.html" %}
{% block cabeza_base %}
    {# Enviar mensaje con los datos al server #}
    <script 
    src="{{ url_for('static', filename='js/enviarLogin.js') }}">
    </script>
    {# Script necesario parainterpretar
    respuestas del servidor. Requerido por
    enviarLogin.js#}
    <script 
    src="{{ url_for('static', filename='js/respuestasServidor.js') }}">
    </script>
	{# OAUTH #}
	{#client id necesaria para emplear API google. Obtenida de fichero
	de credenciales#}
 	<meta name="google-signin-client_id" content="{{id_api}}">
    {# Cargo Scripts Google Oauth2 para utilizar con los botones #}
    <script type=text/javascript src="{{ url_for('static', filename='js/oauth_functions.js') }}"></script>

{% endblock %}

{% block cuerpo_base %}
    <h1>ACCESO</h1>
        {#En los forms, los atributos que identifican a un 
        input text es el name. Es como se identificará en el server.
        P.ej: request.form.get('user') obtendrá el texto
        que haya en el campo de texto con name='user'.#}
        <form id="form_login" action="{{url_for('blueUser.webLogin')}}" method="POST">
            <p>Nombre de usuario:</p>
            <input type="text" id="user" name="user" required="true">
            <br>
            <p>Contraseña:</p>
            <input type="password" id="pass" name="pass" required="true">
            <br>
            <br>
            <button type="submit" id="botonLogin" >Login</button>
        </form>
        {#<a href="{{url_for('blueOAuth.jsOAuthLogin')}}">
		Acceder con cuenta de Google</a>#}
		{# Custom Google Sign in Button #}
		<div id="my-signin2"
		onclick="validarSignIn()"></div>
		{# Load the Google Platform Library #}
		{#La function renderButton() está definida en oauth_functions.js. Sirve
		para darle estilo al botón.#}
		<script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
        <p>
        <span>¿No estás registrado?</span>
        <a href="{{url_for('blueUser.webRegister')}}">Registrarse</a>
		</p>

        <script>
        //Unicamente recibe una cadena que se empleará como 
        //selector del form. En este caso, '#form_login'
        var selector = '#form_login';
        enviarLoginForm(selector);
        </script>
{% endblock %}

src/templates/register.html
{# register.html #}
{% extends "topbar_empty_base.html" %}
{% block cabeza_base%}
    {# Cargo Scripts para la comprobación de datos#}
	{# Cargo Script para la comprobación del umbral#}
    <script 
    src="{{ url_for('static', filename='js/enviarUmbral.js') }}">
    </script>
	{# Cargo Script para la comprobación del nombre y contraseña#}
    <script 
    src="{{ url_for('static', filename='js/enviarRegister.js') }}">
    </script>
    {# Script necesitado por los scripts enviarumbral.js y 
    enviarRegister.js para interpretar las respuestas del servidor. #}
    <script 
    src="{{ url_for('static', filename='js/respuestasServidor.js') }}">
    </script>

{% endblock %}
{% block cuerpo_base %}
    <h1>Registro</h1>
    <form id="form_register" action="{{url_for('blueUser.webRegister')}}" method="POST">
        <p>Nombre de usuario:</p>
        <input type="text" id="user" name="username" required="true">
        <br>
        <p>Contraseña:</p>
        <input type="password" id="pass" name="password" required="true">
        <br>
        <p>Repita su contraseña:</p>
        <input type="password" id="passRep" name="passRep" required="true">
        <br>
        <p>Umbral (número del 0 al 100):</p>
        <input type="text" id="umbral" name="umbral" required="true">
        <br>
        <br>
        <button type="submit" id="boton_registro">Registrar</button>
    </form>
    <br>
    <a href="{{url_for('blueUser.webLogin')}}">Atrás</a>
    <script>
        /*
        $("#boton_registro").click(function()
        {
            var name = $("#user").val();
            var pass = $("#pass").val();
            var passRep = $("#passRep").val();
            var umbral = $("#umbral").val();
            comprobarRegistro(name,pass,passRep,umbral);
        });
        */
        var selector = "#form_register";
        comprobarRegistroForm(selector);
    </script>
{% endblock %}